# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 07:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_speech'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speech',
            name='voices',
        ),
        migrations.DeleteModel(
            name='speech',
        ),
        migrations.DeleteModel(
            name='voice',
        ),
    ]
